version: '3'
services:
  dispatcher:
    image: octoblu/meshblu-core-dispatcher
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URI=redis://redis:6379
      - CACHE_REDIS_URI=redis://redis:6379
      - FIREHOSE_REDIS_URI=redis://redis:6379
      - MONGODB_URI=mongodb://mongo:27017/meshblu
      - JOB_LOG_REDIS_URI=redis://redis:6379
      - TOKEN=meshblu-test-pepper
      - PRIVATE_KEY_BASE64=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBenNZYS9mdi9NVFdkeTRwMUhLVDlpb0FTNStaTHdjY0RIWDYxN3FtUXN2MzhFdXVVCjdkSGUvWTNDeWpkZ1pxU1pZcmxySDkwMVIwTUFhdFoxd2xleWN5ZHV1KzJNWVZlRmtqSlBmajN1UUdkUHJ2bTgKWDQ4VlVEenU2b002bm96ZUFINFVUNEpoVEwraTlKZmROOE9KRVozMzd6MlpHMDZ4Sk04R1BZNWVxWVhidExsMgpmbDErTW55RDlLVWozQ2xCR1I1bkFTczVhUWhadWowN3ZQUnQrREF5ZmtqYmhaakc2V0dEc2RIaGhpdFpLNC9NCkR1enc2c2pOcUJQdjBDQzBtT3EyTEw5OGttWjk2TFJEM0pJbHZSdzl1Y3RUallyVUpOemNJRUJ4Q3h1cjllQ3oKVnlYRWtib09QanZTTUZaT1pkeXVyckR5UmNVU3ZwK2NYZUVPZ1FJREFRQUJBb0lCQUJyRlVWZFMyZjVnQjdjRApqUmdSVUhZdkVNT1BjSDE5SzYwVTY2OGpxd1ZSbHVKSU4vYjJkaDF6emlWcU9BUHlDWjNiamNBSlhzMkVJaml5CjNYbzA2bmk0UVVENWgzUk81WTlCRGtPMDl2VEZxMjVuRFBsK1IrOGtoSFkrV1VlUHkycGE2SHhHMEJ3a3I0OWwKWGhITE1pTGl4ZWZtbkwwSldpdisxYnNBaE1jRHZ2VGhKWnp4Z0F5T01Va1JKMGwxdUVlbzlmelZqQ2JjRThsMAo2dDdnOXdSbEd2WXVJdllLWmpoR094UzhFRVlrS1Z3RXJxdG8vMmM4dm0rSmpNaHkvQU92MUFKcCtGTHNCenBwCkQzcS9NUmM5eEdFV2U3S3NyNi9xdGpmVDY4dHdUT2FtVVdQc0U2aXlDYnNCNDR6aHQ3VjJWRURELzFhT3Y5WEoKNnhlL0xYRUNnWUVBOVRtdm5FdE5TYnd5NFBCL0NlWHA4Ym1aL1JHbXNDd2JUZkxkeG1heHNPZlUzNUtBU3NmOQpJZERFTzV2RjhEOUZkUXdyMmZpNzVSbEM1Nms3SCtqbmpBN09OanUvRVZPQytVMzY2QnRSemZhVlRidEhzM2dHCkQ4Z1Jra3RBdnRqNUc0MkdldUl2c3V3bmZob2Z1OVdaWG56Z1c4RkQ4eEY5b1AyT2lXV1BUbjBDZ1lFQTE5dnEKQWRkZTNGVEthVE54akZJODl1NUhWQkZpSy85bWpncGtMMi9wTWNqQjdLSVNzT1hCSzIxQ296UUlPekIvZ1pROQpzc2tOL2tPKzN2VUt0SUlST25EVk54SkgzeHJxRnpqQUhybVpETmtkM1J5UmltTHM3NnR3QkhQdlV4M1R2MXJqCnZQMkgzZ2YveE5Gc1BBdDRsUTlrWEp3RVpDdGdRMTJDbkZraEsxVUNnWUFCckM0TmM5b0lHYmVESDBET2tYbmkKQXpFUXI5RWlQSHJITWxQZTZZNW10WDRYTkVtWnVQbDZCSkdDRXBMc0M1SnV0UEdMb0Eyd0IxY1VlMndDMExUYgptTEpCWG5EMExreWpaS3ZFYjRORVUxMDdWWDZzczdIZTQ2OXkvdjVuRHRYTUlVLzhnSlJ3dFBtais0dWgzVmdaCmMrS1gzWjZZQnRPRGlKY3pTclVLaFFLQmdESW80eWJNWWptMjVsWXQ0eHZsWEU5UkxYZ0dsaFo5UWRxTjVadjAKV0c3K0pMb1ZLMXk1OXZwZGFGZStWbzlTaEw2YXNQK2pvc0hNQWtXVEVZckNrcmhPMGV6N0xZSlZvY0lGcVBjNgp6NnJocFFQbGlKaHN4bnduRFYrcmhSaCtYTjhoZ3J3KytkeUpaVkRhRFZtaW5NR2Vrd2JHSm1zVWZVa0tLTGltCktZUUZBb0dBQU9ieFU2d0Y2YzZobURrMkczQmh0SjI3b1BEa1RsUEg0V3dDYUpaMXhvTkdnSWs4cjVEUkR5aVgKelF3SnJPYmJhTXlMbkUxenJPMU83QWJseEdVUnRhbm5qUTR1WUlsbDRLWEVnQTBNWnVlUnlFU1dURnM4TVNtbQpaMXIxRVJSQVVHeG5nVE9aNkY2WFlsaW45eEtaZ0NyUmxDbng4VFRZazNRTDBHZEk5WEk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
      - PUBLIC_KEY_BASE64=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6c1lhL2Z2L01UV2R5NHAxSEtUOQppb0FTNStaTHdjY0RIWDYxN3FtUXN2MzhFdXVVN2RIZS9ZM0N5amRnWnFTWllybHJIOTAxUjBNQWF0WjF3bGV5CmN5ZHV1KzJNWVZlRmtqSlBmajN1UUdkUHJ2bThYNDhWVUR6dTZvTTZub3plQUg0VVQ0SmhUTCtpOUpmZE44T0oKRVozMzd6MlpHMDZ4Sk04R1BZNWVxWVhidExsMmZsMStNbnlEOUtVajNDbEJHUjVuQVNzNWFRaFp1ajA3dlBSdAorREF5ZmtqYmhaakc2V0dEc2RIaGhpdFpLNC9NRHV6dzZzak5xQlB2MENDMG1PcTJMTDk4a21aOTZMUkQzSklsCnZSdzl1Y3RUallyVUpOemNJRUJ4Q3h1cjllQ3pWeVhFa2JvT1BqdlNNRlpPWmR5dXJyRHlSY1VTdnArY1hlRU8KZ1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  worker-webhook:
    image: octoblu/meshblu-core-worker-webhook
    depends_on:
      - redis
      - dispatcher
    environment:
      - REDIS_URI=redis://redis:6379
      - JOB_LOG_REDIS_URI=redis://redis:6379
      - PRIVATE_KEY_BASE64=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBenNZYS9mdi9NVFdkeTRwMUhLVDlpb0FTNStaTHdjY0RIWDYxN3FtUXN2MzhFdXVVCjdkSGUvWTNDeWpkZ1pxU1pZcmxySDkwMVIwTUFhdFoxd2xleWN5ZHV1KzJNWVZlRmtqSlBmajN1UUdkUHJ2bTgKWDQ4VlVEenU2b002bm96ZUFINFVUNEpoVEwraTlKZmROOE9KRVozMzd6MlpHMDZ4Sk04R1BZNWVxWVhidExsMgpmbDErTW55RDlLVWozQ2xCR1I1bkFTczVhUWhadWowN3ZQUnQrREF5ZmtqYmhaakc2V0dEc2RIaGhpdFpLNC9NCkR1enc2c2pOcUJQdjBDQzBtT3EyTEw5OGttWjk2TFJEM0pJbHZSdzl1Y3RUallyVUpOemNJRUJ4Q3h1cjllQ3oKVnlYRWtib09QanZTTUZaT1pkeXVyckR5UmNVU3ZwK2NYZUVPZ1FJREFRQUJBb0lCQUJyRlVWZFMyZjVnQjdjRApqUmdSVUhZdkVNT1BjSDE5SzYwVTY2OGpxd1ZSbHVKSU4vYjJkaDF6emlWcU9BUHlDWjNiamNBSlhzMkVJaml5CjNYbzA2bmk0UVVENWgzUk81WTlCRGtPMDl2VEZxMjVuRFBsK1IrOGtoSFkrV1VlUHkycGE2SHhHMEJ3a3I0OWwKWGhITE1pTGl4ZWZtbkwwSldpdisxYnNBaE1jRHZ2VGhKWnp4Z0F5T01Va1JKMGwxdUVlbzlmelZqQ2JjRThsMAo2dDdnOXdSbEd2WXVJdllLWmpoR094UzhFRVlrS1Z3RXJxdG8vMmM4dm0rSmpNaHkvQU92MUFKcCtGTHNCenBwCkQzcS9NUmM5eEdFV2U3S3NyNi9xdGpmVDY4dHdUT2FtVVdQc0U2aXlDYnNCNDR6aHQ3VjJWRURELzFhT3Y5WEoKNnhlL0xYRUNnWUVBOVRtdm5FdE5TYnd5NFBCL0NlWHA4Ym1aL1JHbXNDd2JUZkxkeG1heHNPZlUzNUtBU3NmOQpJZERFTzV2RjhEOUZkUXdyMmZpNzVSbEM1Nms3SCtqbmpBN09OanUvRVZPQytVMzY2QnRSemZhVlRidEhzM2dHCkQ4Z1Jra3RBdnRqNUc0MkdldUl2c3V3bmZob2Z1OVdaWG56Z1c4RkQ4eEY5b1AyT2lXV1BUbjBDZ1lFQTE5dnEKQWRkZTNGVEthVE54akZJODl1NUhWQkZpSy85bWpncGtMMi9wTWNqQjdLSVNzT1hCSzIxQ296UUlPekIvZ1pROQpzc2tOL2tPKzN2VUt0SUlST25EVk54SkgzeHJxRnpqQUhybVpETmtkM1J5UmltTHM3NnR3QkhQdlV4M1R2MXJqCnZQMkgzZ2YveE5Gc1BBdDRsUTlrWEp3RVpDdGdRMTJDbkZraEsxVUNnWUFCckM0TmM5b0lHYmVESDBET2tYbmkKQXpFUXI5RWlQSHJITWxQZTZZNW10WDRYTkVtWnVQbDZCSkdDRXBMc0M1SnV0UEdMb0Eyd0IxY1VlMndDMExUYgptTEpCWG5EMExreWpaS3ZFYjRORVUxMDdWWDZzczdIZTQ2OXkvdjVuRHRYTUlVLzhnSlJ3dFBtais0dWgzVmdaCmMrS1gzWjZZQnRPRGlKY3pTclVLaFFLQmdESW80eWJNWWptMjVsWXQ0eHZsWEU5UkxYZ0dsaFo5UWRxTjVadjAKV0c3K0pMb1ZLMXk1OXZwZGFGZStWbzlTaEw2YXNQK2pvc0hNQWtXVEVZckNrcmhPMGV6N0xZSlZvY0lGcVBjNgp6NnJocFFQbGlKaHN4bnduRFYrcmhSaCtYTjhoZ3J3KytkeUpaVkRhRFZtaW5NR2Vrd2JHSm1zVWZVa0tLTGltCktZUUZBb0dBQU9ieFU2d0Y2YzZobURrMkczQmh0SjI3b1BEa1RsUEg0V3dDYUpaMXhvTkdnSWs4cjVEUkR5aVgKelF3SnJPYmJhTXlMbkUxenJPMU83QWJseEdVUnRhbm5qUTR1WUlsbDRLWEVnQTBNWnVlUnlFU1dURnM4TVNtbQpaMXIxRVJSQVVHeG5nVE9aNkY2WFlsaW45eEtaZ0NyUmxDbng4VFRZazNRTDBHZEk5WEk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  firehose-socketio:
    image: octoblu/meshblu-core-firehose-socket.io
    depends_on:
      - redis
      - dispatcher
      - worker-webhook
    environment:
      - REDIS_URI=redis://redis:6379
      - FIREHOSE_REDIS_URI=redis://redis:6379
  protocol-adapter-http:
    image: octoblu/meshblu-core-protocol-adapter-http
    depends_on:
      - redis
      - dispatcher
      - worker-webhook
      - firehose-socketio
    environment:
      - REDIS_URI=redis://redis:6379
      - CACHE_REDIS_URI=redis://redis:6379
      - JOB_LOG_REDIS_URI=redis://redis:6379
    ports:
      - '3000:80'
  mongo:
    image: mongo
    expose:
      - '27017'
  redis:
    image: redis
    expose:
      - '6379'
